stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "hello, world!"

test-count:
  stage: test
  script:
    - echo "Testando"

deploy-job:
  stage: deploy
  script:
    - echo "Terminou"
