name: pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

jobs:       
   build-job:
        stage: build
        script:
            - echo "hello, world!"

   test-count:
        stage: test
        script:
            - echo "Testando :D"

   deploy-job:
        stage: deploy
        script:
            - echo "Terminou!"
